### ISSUE TITLE
The provided client is not usable for implicit OAuth. Please use the code grant.

### ISSUE THREAD

**Issue by AlexanderKozhevin** [WatchBeam/implicit-oauth-example#4]
I created application inside https://mixer.com/lab/oauth
Formed OAUTH url, and got this error after granting permissions. 

```
The provided client is not usable for implicit OAuth. Please use the code grant.
```

It works only if I use 'response_type=code'
But for 'response_type=token', it gives an error. 

How to fix it?

**Comment by ProbablePrime** [comment]
When creating an OAuth Application, you have the option of checking a "Use Secret" checkbox when doing this it prevents you from using the implicit flow as the implicit flow is not compatible with OAuth Secrets.

To use the implicit flow please re-create your OAuth Application and ensure the "Use Secret" box is unchecked.
